### ISSUE TITLE
create-reat-app

### ISSUE THREAD

**Issue by paulvollmer** [freetzing/fritzing-js#1]
### Context:
bootstrap the project

## Next Steps:
- [ ] add css framework
- [ ] add react project
- [ ] react router
- [ ] style docs
- [ ]  include FZZ, FZP modules
- [ ] renderer modules
  - [ ] breadboard renderer
  - [ ] pcb renderer
  - [ ] schematic renderer

**Comment by paulvollmer** [comment]
@el-j  can you start with the react app setup ^^ at the root of the repository.
skip the renderer modules point or let me know if you need it. i'm working on a first version.

**Comment by karpawich** [comment]
I'm closing this issue because work on a UI and application has transitioned to the **[freetzing](https://github.com/freetzing/freetzing)** repository. The functionality of this library is now limited to just data conversion so that we can break down our work and modularize it.
