### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by karpawich** [freetzing/fritzing-js#12]
`fritzing-js` should be written in TypeScript to support type-checking for all of the given data models.

- ❌ Rewrite in TypeScript
- ❌ Configure Jest

**Comment by karpawich** [comment]
@KingDarBoja good idea to write it in TypeScript. I've created this Issue to officially include your work in the project timeline. Once when you have completed converting it over, submit a PR and we can work in integration with Jest.

**Comment by karpawich** [comment]
@KingDarBoja what is your email? I can add you to the Slack group.

**Comment by KingDarBoja** [comment]
@karpawich It is stevenbojato04@gmail.com :)

**Comment by karpawich** [comment]
Closing because the TypeScript version has been completed.
