### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by paulvollmer** [freetzing/fritzing-js#2]
create a navbar we can use for a wide range of apps. i think a good solution can be a search / command bar like interface. if hyou click on the input, a container drop down and you can customize the ui at this point.

i think it can be a good first navbar component we can fast build and easy customize. i can layout the component later. for next let's discuss the idea...

Phase 1:
- [ ] create first design
- [ ] write component
- [ ] write component demo

Phase 1:
- [ ] create views catalog (list, mosaik, table...) for the dropdown container.
- [ ] create a command manager and connect to input field (call it at the demo to log/alert a message)

## Mockup
<img width="966" alt="screen shot 2018-03-08 at 22 14 52" src="https://user-images.githubusercontent.com/235200/37196841-a7e688b8-2378-11e8-8c33-c9834c7a6fa6.png">

<img width="1031" alt="screen shot 2018-03-08 at 22 15 32" src="https://user-images.githubusercontent.com/235200/37196847-acb46ad6-2378-11e8-915c-123cb591700a.png">

**Comment by karpawich** [comment]
See Issue #1 for why I am closing this issue and others.
