### ISSUE TITLE
Running the fritzing-js app

### ISSUE THREAD

**Issue by Nauman3S** [freetzing/fritzing-js#3]
How can I compile and run the Fritzing-js project?
NPM is not working because of access right for linked repos
below is the output of npm install

npm ERR! Command failed: git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:fritzing/fzz-js.git /home/ubuntu/.npm/_git-remotes/git-github-com-fritzing-fzz-js-git-develop-3926d274
npm ERR! Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-fritzing-fzz-js-git-develop-3926d274'...
npm ERR! Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/fr/fritzing-js/npm-debug.log

**Comment by karpawich** [comment]
This issue is off topic. An answer to the OP's question can be better answered over at StackOverflow.
