### ISSUE TITLE
Looking to Contribute

### ISSUE THREAD

**Issue by ahsan-sabir** [freetzing/fritzing-js#4]

**Comment by Ahsan2** [comment]
Appreciate the effort of bringing fritzing to the wonderful world of javascript,
and would like to be a part of that. I know JavaScript and familiar with React.
Looking forward to the opportunity.
Thanks

**Comment by karpawich** [comment]
@Ahsan2 See the README for how you can contribute.. you can start by submitting a Pull Request with changes (updates, bug fixes, etc.) that you want to make to improve this library. Thanks for expressing interest. I'm sorry that it took so long for us to get back to you.
