### ISSUE TITLE
The future...

### ISSUE THREAD

**Issue by karpawich** [freetzing/fritzing-js#6]
A few months ago, I wrote the following TODO list for future modifications:

- Helper functions
- Publish to NPM
- Documentation
- Testing
- Rendering
    - Parts
    - Sketches
- Full-scale application
    - Editing
    - Autorouting

@el-j 

1. Let me know your thoughts on the TODO list so I can go ahead.
2. How often will you check / update / work on this repository?
3. If you can't dedicate a lot of time to the project, perhaps give me push perms so I can merge my own changes?

**Comment by el-j** [comment]
hi, there. that sounds great. lets move ;)
https://github.com/freetzing/fritzing-js

**Comment by karpawich** [comment]
Closing this issue because I opened it :)
