### ISSUE TITLE
missing utils from fzp-js

### ISSUE THREAD

**Issue by el-j** [freetzing/fritzing-js#8]
there where really good features already written in the fzp-js library.

mybe we should make fritzing-js more a collection of this repositories. so we can have all things in small modules combined here together.
@karpawich what do you think about that?

there were things like:

`FZPUtils.loadFZPandSVGs('core/Arduino Nano3(fix).fzp')`

look at this: https://fritzing.github.io/fzp-js/
Good documentation is the best...
https://github.com/fritzing/fzp-js/blob/master/src/utils.js

**Comment by karpawich** [comment]
@el-j I definitely love the documentation of the `fzp-js` library, and I think that we definitely need to working on documenting `fritzing-js` in full as well. _However_, I don't think that we need to separate it into multiple repositories, given that each repository would serve the same function: **converting old Fritzing data files into Javascript models**. 

That said, I think we could definitely separate each section (Sketches, Parts, Bundles, etc.) into its own _Javascript module_, and then import them as needed. I have never encountered a Javascript library that separates its modules into different repositories, though. Does that make sense?

I'll create a new issue with a feature request for library modularity, documentation, and incorporating the SVG-loading capabilities of the `fzp-js` library.

**Comment by karpawich** [comment]
See Issue #10 for an expansion of this issue.
