### ISSUE TITLE
require needs total path

### ISSUE THREAD

**Issue by el-j** [freetzing/fritzing-js#9]
you need to require the module from the total-path with ./node_modules

`const Fritzing = require ('./node_modules/fritzing-js/fritzing.js')`

should be

`const Fritzing = require ('fritzing-js')`

**Comment by karpawich** [comment]
Part of the TODO involves publishing this as an NPM repository. I'll also include that in the feature request issue.

**Comment by karpawich** [comment]
See Issue #10 for an expansion on this issue.
